name: marc
favicon: null
layout_spectrum: 0.5140682077035308
typography_spectrum: 0.7314696491230279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7162232361733913
  lightness: 0.09233589447103441
  saturation: 0.29316637362353504
  rhythmicContrast: 0.7728406279347837
purpose: []
